"""profile_fact table

Revision ID: 86386f9b0e3c
Revises: 0742ed8562ba
Create Date: 2026-07-30 15:51:38.474084

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "86386f9b0e3c"
down_revision: str | None = "0742ed8562ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_fact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidate.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "key", name="uq_profile_fact_candidate_key"),
    )
    op.create_index(
        op.f("ix_profile_fact_candidate_id"), "profile_fact", ["candidate_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_fact_candidate_id"), table_name="profile_fact")
    op.drop_table("profile_fact")
    # ### end Alembic commands ###
